# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='link',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='link',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Episode'),
        ),
    ]
