# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170602_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
