# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_episode_link_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
